# Site settings
title: "Visualization in Data Science (VDS at IEEE VIS)"
email: "vds@ieeevis.org"
description: "Visualization in Data Science (VDS at IEEE VIS 2024)"
baseurl: "/2024"
url: "http://www.visualdatascience.org/"
conferenceshort: "VDS 2024"
conferencedate: "TBD" 

deadline_submission_vis:  "Fri, Jul. 12th, 2024 11:59 pm AOE"
deadline_notification_vis: "Fri, Aug. 9th, 2024 11:59 pm AOE"
event2_date: "TBD"

# Build settings
markdown: kramdown

collections:
- talks

